### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Chandan-Abhyankar**
Fixing compilation issues

### CODE REVIEW

**Review by tuliom — CHANGES_REQUESTED** [review]
@Chandan-Abhyankar , the changes look good to me.
Could you add your `Signed-off-by:`, please?
--- Edit ---
I should also state that the `Signed-off-by:` means that you certify the following:
```
By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

**Comment by Chandan-Abhyankar** [comment]
Can you please check now

**Review by tuliom — APPROVED** [review]

**Review by mscastanho — APPROVED** [review]

**Comment by tuliom** [comment]
@Chandan-Abhyankar I've just merged your patch into branch `develop`.
This patch will automatically be merged into `master` when a new release is available.
If you have a need to reflect this documentation on `master` before that, please let me know.

**Comment by tuliom** [comment]
@Chandan-Abhyankar I should have also said: Thank you!

**Comment by Chandan-Abhyankar** [comment]
> @Chandan-Abhyankar I've just merged your patch into branch `develop`. This patch will automatically be merged into `master` when a new release is available. If you have a need to reflect this documentation on `master` before that, please let me know.

Thanks for merging code. There is no hurry, let this get merged in master branch whenever new release is planned.

**Pull request merged**
