### PR TITLE
SetDictionary functions need testing before making them available

### PR DESCRIPTION
**Pull request by abalib**
Signed-off-by: Bulent Abali <abali@us.ibm.com>

### CODE REVIEW

**Comment by abalib** [comment]
We didn't test these thoroughly.  We should disable them until then.  I propose to also apply the commit to the master branch as well

**Comment by rzinsly** [comment]
I don't think it's a good idea remove useful functions and functionalities from the library, instead we should test it better and report bugs we encounter, also having it available we can get users data if they found issues.
The codes seems being working ok, have you found any problems?

**Comment by abalib** [comment]
We need to run regression to make sure deflateSetDictonary output can be correctly decompressed.  I am still looking for the source data that failed.  The test is found here  https://github.com/libnxz/power-gzip/blob/develop/samples/dict-test.sh

**Comment by abalib** [comment]
Thank you. I am going to setup some test runs to reproduce fails.  I assume it's ok to merge PR for now?

**Comment by rzinsly** [comment]
> Thank you. I am going to setup some test runs to reproduce fails. I assume it's ok to merge PR for now?

Yes

**Comment by abalib** [comment]
I will look for the test case.  But regardless I recognized later that my dictionary design and logic might be incorrect.   The worst thing we can do is giving users code that sometimes compresses incorrectly, and they cannot decompress their data later.  Until we fix this path, we should return an error.  Allow me to read the code and I come back with a better explanation and perhaps a design.

**Pull request merged**
